dict = {
    "1. The term 'Renaissance' signifies a 'rebirth' of _______ (also called _______) civilization.": "Classical, Greco-Roman",
    "2. The Crusades facilitated contact with the _______ Civilization, which introduced new ideas that challenged Church doctrine.": "Islamic",
    "3. The establishment of _______ in the late Middle Ages fostered critical thinking and reduced the Church's cultural monopoly.": "universities",
    "4. The socioeconomic system that declined as towns rose, breaking the lord-vassal relationship, was _______.": "feudalism",
    "5. _______ were itinerant traders whose activities led to the formation of towns for convenience.": "Peddlers",
    "6. The _______ was an association that protected the interests of merchants and craftsmen in medieval towns.": "guild",
    "7. The policy stating a serf living in a town for _______ would gain freedom accelerated the decline of manorial labor.": "one year",
    "8. The _______ killed one-third of Europe's population, causing a severe manpower shortage that further impoverished the nobility.": "Black Death",
    "9. The _______ was invented by Gutenberg, making books cheaper and drastically accelerating the spread of ideas.": "movable metal type printing press",
    "10. Prior to the printing press, books were expensive because they were laboriously copied as _______.": "manuscripts",
    "11. The primary reason the Renaissance began specifically in Italy, beyond wealth, was the influx of scholars after the fall of _______.": "Constantinople",
    "12. Renaissance humanism shifted focus from the afterlife to improving one's _______.": "life on earth",
    "13. In art, the medieval use of a flat, golden background contrasts with the Renaissance use of detailed _______.": "natural landscape",
    "14. The artistic technique of using light and shade to create three-dimensional, life-like figures is called _______.": "chiaroscuro",
    "15. The artistic device used to create an illusion of depth and distance on a flat surface is _______.": "perspective",
    "16. Leonardo da Vinci's 'Mona Lisa' is celebrated for its _______ human figures, demonstrating high technical skill.": "lively",
    "17. Raphael's 'The School of Athens' reflects the Renaissance pursuit of _______ as a daily-life theme.": "knowledge",
    "18. Michelangelo's sculptures 'David' and 'The Pieta' exemplify the Renaissance focus on _______ and realistic human forms.": "human-centered themes",
    "19. Medieval Gothic architecture is characterized by _______ spires and pointed arches.": "pointed",
    "20. Notre Dame in Paris is a prime example of _______ architecture.": "Gothic",
    "21. Renaissance architecture revived the use of tall columns, round arches, and large round _______ from classical designs.": "domes",
    "23. Unlike medieval literature, Renaissance writers like Shakespeare explored themes of love and _______.": "injustice in society",
    "24. The Church's significant political power in the Early Middle Ages came from its role in giving _______ to the king.": "advices",
    "25. The Church's ultimate religious punishment, involving being burned alive for holding contrary beliefs, was accusation of _______.": "heresy",
    "26. The decline of the nobility's economic power was marked by their need to _______ laborers after serfs left for towns.": "employ/pay",
    "27. Towns attracted serfs because they offered more freedom and protection through _______ and town governments.": "guilds",
    "28. During the Black Death, some people practiced self-harm, believing the plague was a _______ from God.": "punishment",
    "29. The key philosophical shift of the Renaissance was from a God-centered worldview to a _______ worldview.": "human-centered",
    "30. The use of rich, warm colors in Renaissance paintings contrasted with the darker, fewer colors typical of _______ art.": "medieval",
    "31. A triangular gable found on classical and Renaissance buildings is called a _______.": "pediment",
    "32. The primary function of most large Gothic buildings was _______, whereas Renaissance buildings served diverse secular purposes.": "religious/church",
    "33. The ability to develop independent thought and question authority was a direct challenge to the Church's _______ power.": "cultural",
    "34. The economic foundation of Italian city-states that allowed merchants to patronize artists was _______.": "trade/increasing trades",
    "35. The rigid, static depiction of human figures in medieval art contrasts with the _______ figures of Renaissance art.": "realistic",
    "36. The vaulted roof is a distinctive architectural feature of the _______ style.": "Gothic",
    "37. The long, narrow windows with colored stained glass are characteristic of _______ cathedrals.": "Gothic",
    "38. The Florence Cathedral, with its large dome, is a landmark of _______ architecture.": "Renaissance",
    "39. The belief that men were 'sinners' and 'insignificant' was a typical view of people during the _______.": "Early Middle Ages",
    "40. The Renaissance emphasis on human ability and creativity is a core tenet of _______.": "Humanism",
    "41. The primary educational language in medieval universities was _______, even as they taught secular subjects.": "Latin",
    "42. The trade expeditions and wars known as the _______ opened new routes and ideas from the East.": "Crusades",
    "43. The visual difference between a flat medieval painting and a Renaissance one with depth is due to the use of _______.": "perspective",
    "44. The wealth generated in towns came primarily from _______, which also financed artistic patronage.": "trades/trade",
    "45. The concept that 'life on earth' is valuable and worth improving is a ________ idea, not a medieval one.": "Humanist",
    "46. The artistic shift from solely religious themes to _______ themes reflects Renaissance humanism.": "daily life",
    "47. The architectural element of a large, round _______ on the Florence Cathedral required advanced engineering skill.": "dome",
    "48. The literary achievement of William Shakespeare included creating new _______, showcasing human creativity.": "words",
    "49. The primary reason nobles became poor in the late Middle Ages was the waste of their _______ due to a lack of serfs to farm them.": "lands",
    "50. The fundamental cause for the Renaissance beginning in Italy, combining wealth and classical knowledge, was the fall of _______ in 1453.": "Constantinople"
}
import revisionHelper as rh
rh.ask_questions(dict)  # Ask the user questions based on the dictionary